# coding: utf8
"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from math_tools import triangles, pentagons, hexagons

t = set(triangles(100000))
p = set(pentagons(100000))
h = set(hexagons(100000))

results = (t.intersection(p)).intersection(h)
print sorted(results)[2]

"""
real	0m0.082s
user	0m0.064s
sys	0m0.013s
"""