# coding: utf8
"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""

def pentagonal(n):
	return [x*(3*x-1)/2 for x in xrange(1,n+1)]

ps = pentagonal(3000)
ps_set = set(ps)

results = dict()
found = False
for i in xrange(0,len(ps)):
	for j in xrange(i, len(ps)):
		if ps[i] + ps[j] in ps_set and ps[j] - ps[i] in ps_set:
		# if sm in ps_set and df in ps_set:
			# results[(ps[i],ps[j])] = ps[j] - ps[i]
			print ps[j] - ps[i]
			found = True
	if found:
		break

"""
real	0m0.302s
user	0m0.293s
sys	0m0.005s
"""