"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def even(x):
	if x % 2 == 0:
		return True
	return False

def gen_fibs():
	fibs = [1,2]
	while fibs[-1] + fibs[-2] < 4e6:
		fibs.append(fibs[-1] + fibs[-2])
	return fibs

fibs = gen_fibs()

even_fibs = filter(even, fibs)

ans = sum(even_fibs)

print ans